### ISSUE TITLE
`process_custom_shift_keys` goes call before `process_sentence_case` in `keymap.c`

### ISSUE THREAD

**Issue by NikGovorov** [getreuer/qmk-keymap#34]
Hello @getreuer,

I'm not certain if it was done intentionally, but I noticed it and decided to create an issue just in case. Please feel free to close the issue if it was intended.

> Note: If you happen to also use [custom shift keys](https://getreuer.info/posts/keyboards/custom-shift-keys/index.html), be sure to call process_sentence_case() before process_custom_shift_keys().

Thanks for the great QMK features and userspace libs, I wouldn't be able to use home row mods without Accordion!

**Comment by getreuer** [comment]
@NikGovorov thanks for catching this! And so sorry for the late reply.

You are right, `process_sentence_case()` should be called before                                                                                                         `process_custom_shift_keys()`.  Otherwise, in the opposite order, Sentence Case would not have a                                                                                                  
chance to process key events where a custom shift key was pressed. This                                                                                                   
is a problem especially if—and as is the case in my keymap—a custom                                                                                                   
shift key is used to type sentence-ending punctuation. So correct order                                                                                                   
of these feature handlers matters. Yet I failed to follow my own rule. 

Thanks again!
