### ISSUE TITLE
[Bug]  Issues with newest version of QMK, Achordion and combos

### ISSUE THREAD

**Issue by jweickm** [getreuer/qmk-keymap#38]
## Background
The newest versions of QMK introduced a number of breaking changes. 
Most notably:
- Introduction of Repeat key feature (congratulations!)
- Deprecation of IGNORE_MOD_TAP_INTERRUPT (https://github.com/qmk/qmk_firmware/blob/master/docs/ChangeLog/20230528.md#ignore_mod_tap_interrupt-behaviour-changes-20211-idi-m-t-i)

I have been happily using Achordion with homerow mods on my Planck/Rev6 for a long time now. After updating to the newest version of QMK, I was prompted to remove the line `#define IGNORE_MOD_TAP_INTERRUPT` from my config.h, since it was deprecated. 

## Bug description
- <kbd>LCTL_T(KC_T)</kbd> mapped on the homerow (left hand).
- <kbd>KC_H</kbd> + <kbd>KC_COMM</kbd> mapped as a combo for <kbd>KC_ENT</kbd> (right hand).

I expect pressing and holding <kbd>LCTL_T(KC_T)</kbd> and then tapping <kbd>KC_H</kbd> + <kbd>KC_COMM</kbd> to trigger <kbd>KC_LCTL</kbd> + <kbd>KC_ENT</kbd>. 

However, after flashing, I observe the following issue:
Instead of outputting <kbd>KC_LCTL</kbd> + <kbd>KC_ENT</kbd>, it outputs <kbd>KC_T</kbd> followed by <kbd>KC_ENT</kbd>.

This issue happens with all combinations of homerow mods on the left hand side and combos on the right hand side of the keyboard. Oddly enough, the same is not true for the opposite. 
I suspect that it has something to do with the newest changes to IGNORE_MOD_TAP_INTERRUPT, but of course  it could also be something completely different. 

## Information

**Do the keys involved use any of the following features?**
 - [x] Achordion (from this repo)
 - [ ] Auto Shift
 - [x] Combos
 - [ ] Key Overrides
 - [x] Mod-tap or Layer-tap keys
 - [ ] Other custom userspace code:

**Comment by getreuer** [comment]
@jweickm, apologies for the long delay!

This bug appears to be the same as bug #50. This should be fixed by 15146c388afd6980d752c2fa8409a19bb46383cc. Please `git pull` or grab the latest copy of [features/achordion.c](https://github.com/getreuer/qmk-keymap/blob/main/features/achordion.c) and see whether that fixes it.

In 2022, QMK changed how combo events are represented and added an `IS_KEYEVENT` API. Achordion added a backwards compatibility check for the existence of this API, but this was improperly implemented and was unconditionally using the pre-2022 logic. Now that it's 2024, the fix is to dump this busted backwards compatibility check and simply use `IS_KEYEVENT` directly.
